// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const {demo} = require('../utils/utils');

describe('INICIAR TEST REGISTRO DE PROFESOR', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('REGISTRO DE PROFESOR', async function() {
    await driver.get("https://profelitebolivia.web.app/")
    await driver.manage().window().setRect({ width: 1138, height: 895 })
    await driver.findElement(By.css(".MuiButtonBase-root:nth-child(2) > .MuiButton-label")).click()
    await driver.findElement(By.xpath("//input[@type=\"email\"]")).click()
    await driver.findElement(By.xpath("//html/body/div[4]/div[3]/div/form/div[1]/div[2]/div[1]/div/input")).sendKeys("test@gmail.com")
    await driver.findElement(By.xpath("//input[@type=\'password\']")).click()
    await driver.findElement(By.xpath("//html/body/div[4]/div[3]/div/form/div[1]/div[2]/div[2]/div/input")).sendKeys("test")
    await driver.findElement(By.css(".MuiDialogActions-root")).click()
    await driver.findElement(By.css(".jss44:nth-child(2)")).click()
    await demo();
    await demo();
    await driver.findElement(By.xpath("//*[@id=\"root\"]/div/nav/div[2]/div/div/div/ul/a[2]")).click()
    await driver.findElement(By.css(".MuiInputBase-multiline")).click()
    await driver.findElement(By.xpath("//*[@id=\"root\"]/div/div[4]/div[3]/div/div[2]/form/div[1]/div/div/div[1]/div/div/div/textarea[1]")).sendKeys("Soy un profesor de Prueba")
    await driver.findElement(By.css(".Mui-focused > .MuiInputBase-input")).click()
    await driver.findElement(By.xpath("//*[@id=\"root\"]/div/div[4]/div[3]/div/div[2]/form/div[1]/div/div/div[2]/div/div/div/input")).sendKeys("77000077")
    await driver.findElement(By.xpath("//*[@id=\"root\"]/div/div[4]/div[3]/div/div[2]/form/div[3]/button")).click()
    await demo();
    await driver.close()
  })
})
