// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Registrar materia TEST', function() {
  this.timeout(50000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Proceso de automatización', async function() {
    await driver.get("https://profelitebolivia.web.app/#initial")
    await driver.manage().window().setRect({ width: 1138, height: 895 })

    await driver.findElement(By.css(".MuiButtonBase-root:nth-child(2) > .MuiButton-label")).click()
    await driver.findElement(By.xpath("//input[@type=\"email\"]")).click()
    await driver.findElement(By.xpath("//html/body/div[4]/div[3]/div/form/div[1]/div/div[1]/div/input")).sendKeys("testuno@gmail.com")
    await driver.findElement(By.xpath("//input[@type=\'password\']")).click()
    await driver.findElement(By.xpath("//html/body/div[4]/div[3]/div/form/div[1]/div[2]/div[2]/div/input")).sendKeys("testuno")
    await driver.findElement(By.css(".jss44:nth-child(2) > .MuiButton-label")).click()
    await demo();
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/nav/div[2]/div/div/div/ul/a[2]/div")).click()
    await driver.findElement(By.xpath("//*[@id=\"root\"]/div/div[4]/div[3]/div/div[3]/form/div[1]/div[1]/div/div/input")).sendKeys("Curso 1")
    await driver.findElement(By.css(".Mui-focused > .MuiInputBase-input")).click()
    await driver.findElement(By.xpath("//*[@id=\"root\"]/div/div[4]/div[3]/div/div[3]/form/div[1]/div[2]/div/div/textarea")).sendKeys("Prueba automatizada para crear curso")
    //await driver.findElement(By.css("div:nth-child(3) > .MuiFormControl-root > .MuiInputBase-root")).click()
    await driver.findElement(By.xpath("//*[@id=\"root\"]/div/div[4]/div[3]/div/div[3]/form/div[1]/div[3]/div/div/textarea")).sendKeys("Este es un curso de prueba para la automatización de la funcionalidad")
    await driver.findElement(By.xpath("//*[@id=\"root\"]/div/div[4]/div[3]/div/div[3]/form/div[1]/div[4]/div/div/div/div/button[2]")).click()
    await driver.findElement(By.xpath("//html/body/div[5]/div/ul/li[1]")).click()
    await driver.findElement(By.xpath("//*[@id=\"root\"]/div/div[4]/div[3]/div/div[3]/form/div[1]/div[5]/div/div/input")).sendKeys("30")
    demo();
    //await driver.findElement(By.css(".jss125:nth-child(2) > .MuiButton-label")).click()
    await driver.findElement(By.xpath("//html/body/div/div/div[4]/div[3]/div/div[3]/form/div[2]")).click()
    demo();
  })
})
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}
async function demo() {
  await sleep(2000);
}
